version: "3"
services:
  nginx:
    ports:
      - 80:80
  # app-studio:
  #   build: .
  #   ports:
  #     - 5555:5555
  #   depends_on:
  #     - app-server
  #   environment:
  #     - NODE_DEV=development
  #     - DATABASE_URL=postgresql://admin:admin@postgres:5432/nest
  #   command: prisma studio --port 5555 --browser none
  app-server:
    build:
      context: .
      args:
        NODE_DEV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_DEV=development
      - DB_IP=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=nest
    command:
      - sh
      - -c
      - |
        npm run prisma:dev
        npm run dev
