version: "3"
services:
  nginx:
    ports:
      - 80:80
  prisma-studio:
    build:
      context: .
      args:
        NODE_DEV: development
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/nest?schema=public
    ports:
      - 5555:5555
    command: npm run prisma:studio
  app-server:
    build:
      context: .
      args:
        NODE_DEV: development
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_DEV=development
      - DB_IP=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=nest
    command:
      - sh
      - -c
      - |
        npm run prisma:dev
        npm run prisma:generate
        npm run dev
