version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-server
  app-server:
    build: .
    depends_on:
      - postgres                          
  postgres: 
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest
    privileged: true
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis 
volumes:
  postgres-db:
