version: "3"
services:
  nginx:
    ports:
      - 80:80
  app-server:
    build:
      context: .
      args:
        NODE_DEV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_DEV=production 
      - DB_IP=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=admin 
    command:
      - sh
      - -c
      - |
        npm run prisma:generate
        npm run prisma:push
        npm run prisma:deploy
        npm run build 
        npm run prod
